project:
  type: website
  output-dir: docs

website:
  title: "Concesión Onerosa de Derechos por Mayor Edificabilidad"
  navbar:
    left:
      - href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

